create table customers (
    id bigint generated by default as identity primary key,
    name varchar(150) not null,
    segment varchar(50) not null,
    home_region varchar(50) not null
);

create table products (
    id bigint generated by default as identity primary key,
    sku varchar(30) not null unique,
    name varchar(150) not null,
    category varchar(50) not null
);

create table sales_orders (
    id bigint generated by default as identity primary key,
    order_number varchar(30) not null unique,
    order_date date not null,
    customer_id bigint not null,
    product_id bigint not null,
    region varchar(50) not null,
    channel varchar(50) not null,
    quantity integer not null,
    revenue decimal(12, 2) not null,
    cost decimal(12, 2) not null,
    profit decimal(12, 2) not null,
    constraint fk_sales_orders_customer foreign key (customer_id) references customers(id),
    constraint fk_sales_orders_product foreign key (product_id) references products(id)
);

create index idx_sales_orders_order_date on sales_orders(order_date);
create index idx_sales_orders_region_channel on sales_orders(region, channel);

